Feat : setting ui
YouDongKnowMe/YouDongKnowMe-Android pull request #22
Opened 2022-05-10 03:39 UTC by jiwon1454

>설정 화면 UI 구현

2022-05-10 08:10 UTC, jiwon1454 commented on README.md
> -동양미래대 학우들을 위해 여러 정보를 제공해드립니다!
네

2022-05-15 03:32 UTC, hoyahozz requested changes
구현하느라 고생 많으셨습니다 😊
해당 리뷰 외에 이전 리뷰도 함께 수정해주시면 좋을 것 같습니다!
궁금한거 있으면 언제든 물어봐주세요~

2022-05-15 03:32 UTC, hoyahozz commented on app/src/main/res/layout/fragment_setting.xml
> +            android:layout_height="wrap_content"
액션바 사이즈를 고정해두지 않으면 화면에 따라 액션바 사이즈가 달라집니다..!
기존에 있던 액션바 사이즈로 고정해주세요~

2022-05-15 03:32 UTC, hoyahozz commented on app/src/main/res/layout/fragment_setting.xml
> +            app:layout_constraintStart_toStartOf="parent"
```xml
    android:layout_width="match_parent"
```
이미 시작점과 끝점은 체인이 걸려져 있는 상태입니다.

2022-05-15 03:32 UTC, hoyahozz commented on app/src/main/res/layout/fragment_setting.xml
> +        <ScrollView
휴대폰 화면에 따라 스크롤이 내려갈 수 있는 점을 잘 파악해주셨습니당 👍

2022-05-15 03:32 UTC, hoyahozz commented on app/src/main/res/layout/fragment_setting.xml
> +            app:layout_constraintVertical_bias="0.0">
```xml
app:layout_constraintHorizontal_bias="0.0"
app:layout_constraintVertical_bias="0.0"
```

이건 왜 들어간건지 알 수 있을까요? 🤔

2022-05-15 03:32 UTC, hoyahozz commented on app/src/main/res/layout/fragment_setting.xml
> +                    android:paddingLeft="30dp"
`padding` 과 `margin` 의 차이를 알아보면 좋을 것 같아요 :)
또한, 디자인 원칙에 따라 간격은 16dp 로 고정됩니다 😊

2022-05-15 03:39 UTC, hoyahozz commented on app/src/main/res/layout/fragment_setting.xml
> +                <Switch
`Switch` 는 Deprecated 됐습니다!
`SwitchCompat` 으로 수정 부탁드립니다~

2022-05-15 08:19 UTC, jiwon1454 commented on app/src/main/res/layout/fragment_setting.xml
> +            android:layout_height="wrap_content"
넹 수정 할게요~!!

2022-05-15 08:19 UTC, jiwon1454 commented on app/src/main/res/layout/fragment_setting.xml
> +            app:layout_constraintStart_toStartOf="parent"
넵

2022-05-15 08:20 UTC, jiwon1454 commented on app/src/main/res/layout/fragment_setting.xml
> +            app:layout_constraintVertical_bias="0.0">
이거 디자인에서 만지다가 추가된거 같은데 코드 삭제하고 다시 올릴게요!!

2022-05-15 08:20 UTC, jiwon1454 commented on app/src/main/res/layout/fragment_setting.xml
> +                    android:paddingLeft="30dp"
넵 알겠습니당:)

2022-05-15 08:20 UTC, jiwon1454 commented on app/src/main/res/layout/fragment_setting.xml
> +                <Switch
넵!!

2022-05-19 13:20 UTC, hoyahozz requested changes

2022-05-19 13:20 UTC, hoyahozz commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/setting/SettingFragment.kt
> +        binding.settingVersion.text = " ${getAppVersion()}"
```kotlin
 binding.settingVersion.text = getAppVersion()
```

2022-05-19 13:20 UTC, hoyahozz commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/setting/SettingFragment.kt
> +    }
- 베이스에서 선언한 함수 이외에 독립적으로 선언하는 함수는 아래로 내려주시는게 가독성 면에서 좋습니당!
- 추가로 `return packageManager.versionName` <- 이 부분 들여쓰기가 안맞아요!

2022-05-19 13:20 UTC, hoyahozz commented on app/src/main/res/layout/fragment_setting.xml
> +                    android:clickable="true">
클릭했을 때 깜빡이는 UI를 넣어줌으로서 유저에게 "클릭했다" 는 인식을 줄 수 있게 나중에 설정해주세요!

2022-05-19 13:20 UTC, hoyahozz commented on app/src/main/res/xml/settings_preference.xml
> +        <PreferenceCategory
사용하지 않기로 결정한 코드는 삭제해주세요!

2022-05-19 13:20 UTC, hoyahozz commented on app/src/main/res/layout/fragment_setting.xml
> +                        android:id="@+id/appHelp"
**id 를 설정할 때는 컨벤션에 맞게 설정해주세요!**
`"@+id/appHelp"` -> `"@+id/setting_ask"`

2022-05-23 13:18 UTC, merged