Feat : 학사 일정 데이트 피커
YouDongKnowMe/YouDongKnowMe-Android pull request #263
Opened 2024-09-04 03:28 UTC by huiwoo-jo

## 📮 관련 이슈
- resolved #258 

## ✍️ 구현 내용
- 학사 일정 데이트 피커 바텀 시트를 제작하였습니다.
- 현재 일 기준 전년도와 다음년도 2월까지 학사 일정을 확인 할 수 있습니다.
- 데이트 피커로 일정 설정 혹은 화살표로 일정 목록 변경이 가능합니다.
- 일정 날짜 변동에 따라 데이트 피커에 반영되도록 제작하였습니다.

## 📷 구현 영상

https://github.com/user-attachments/assets/67ee7c4d-feb9-4550-99d4-11d0e1b1ff44

## ✔️ 확인 사항
- [x] 컨벤션에 맞는 PR 타이틀
- [x] 관련 이슈 연결
- [x] PR 관련 정보 연결 (작업자, 라벨, 마일스톤 등)
- [ ] Github Action 통과

2024-09-04 09:24 UTC, m6z1 requested changes
코멘트 확인 부탁드려요! 로직을 한 번 더 생각해보시면 좋을 것 같습니다! MVVM을 사용하면 충분히 구현할 수 있을 것 같아용

2024-09-04 09:24 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/DatePickerDialog.kt
> +    private val dateSelectedListener: ScheduleFragment,
다이얼로그를 생성할 때 생성자로 fragment를 꼭 받아야 할까요?? 프래그먼트를 생성자로 받지 않고 다른 방법으로 구현해보시면 좋을 것 같아요 👍

2024-09-04 09:24 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/ScheduleFragment.kt
> +
인터페이스를 분리하면 좋을 것 같아요 👍

2024-09-04 09:24 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/ScheduleFragment.kt
> +    private var month = _month
둘 다 접근제한자가 private인데 프래그먼트에서 배킹프로퍼티를 사용하는 이유가 있나요 ?

2024-09-04 09:24 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/DatePickerDialog.kt
> +    private val viewModel: ScheduleViewModel by viewModel()
학사일정 프래그먼트와 뷰모델을 공유하려면 activityViewModels를 쓰면 될 것 같아요! 따로 다이얼로그에서 뷰모델 인스턴스를 새로 생성하는 이유가 있나요?

2024-09-04 09:24 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/ScheduleFragment.kt
> +            dialog.show(requireActivity().supportFragmentManager, "CustomDialog")
Tag 값은 상수화해서 사용하는 게 좋을 것 같아요! 그리고 커스텀 다이얼로그 보다는 다른 네이밍을 사용하면 좋을 것 같습니당

2024-09-04 09:24 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/ScheduleFragment.kt
> +            dialog.show(requireActivity().supportFragmentManager, "CustomDialog")
`requireActivity`와 `requireContext` 의 차이가 무엇일까요! 어디에는 위에서 컬러값을 가져올 땐 `requireContext`를 사용하셨는데 요기선 `requireActivity` 를 사용하신 이유가 궁금해용

2024-09-04 09:24 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/ScheduleViewModel.kt
> +    fun setDatePicker(year: Int, month: Int) {
메서드명이 `데이트 피커를 세팅해준다`는 말인 것 같아요 실질적인 메서드가 하는 일은 선택한 연도와 월을 업데이트 해주니 메서드명을 변경해보면 어떨까요? 👍

2024-09-04 09:24 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/DatePickerDialog.kt
> +    override fun onCreateView(
fragment의 생명주기에 대해서 알고 계신가요 ? `onCreateView`에서 해야할 일과 `onViewCreated`에서 해야할 일을 분리하면 좋을 것 같슴니다
[참고할 블로그](https://readystory.tistory.com/199)

2024-09-04 09:24 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/DatePickerDialog.kt
> +
메서드를 분리하면 가독성이 더 좋아질 것 같아욥

2024-09-04 09:24 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/DatePickerDialog.kt
> +            displayedValues=((minValue..maxValue).map{"$it 년"}.toTypedArray())
array 타입으로 캐스팅해주시는 이유가 궁금해요!

2024-09-04 09:24 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/DatePickerDialog.kt
> +            // 연도 선택에 따른 월의 최대값 동적 설정
월은 항상 1~12로 고정되어있는데, 연도 선택에 따른 월의 최대값 동적 설정이 필요한 이유가 무엇인가요 ?

2024-09-04 09:24 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/DatePickerDialog.kt
> +            )
MVVM 패턴을 사용하면 이 로직은 없어도 될 것 같아요. 현재 상태는 다이얼로그에서 선택한 값을 fragment로 직접 넘기는 형태이고 뷰모델을 사용하지 않는 것 같습니다! 뷰모델을 사용해서 dialog 의 생성자 중 fragment 를 제거하고, fragment에서도 interface 를 제거하고, 뷰모델에서 observe 받은 값으로만 수정해도 될 것 같아요

2024-09-20 07:30 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/DatePickerDialog.kt
> +    private val dateSelectedListener: ScheduleFragment,
이전에 Dialog를 사용한 부분에서 가져온거라 생각을 못해봤네요 수정해보겠습니다

2024-09-20 07:31 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/ScheduleFragment.kt
> +    private var month = _month
기존 코드들을 참고하여서 배킹 프로퍼티의 의미를 제대로 생각 못한거 같습니다🤔

2024-09-20 07:36 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/DatePickerDialog.kt
> +    private val viewModel: ScheduleViewModel by viewModel()
코드를 살펴보니 별도의 인스턴스를 생성할 이유가 없네요..
익숙한 코드를 사용하여 생각해보지 못한 부분이라 말씀하신 대로 activityViewModels로 수정하겠습니다.

2024-09-20 07:45 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/ScheduleViewModel.kt
> +    fun setDatePicker(year: Int, month: Int) {
그렇게도 해석할 수 있겠네요. 생각해보지 못했습니다.
더 좋은 네이밍을 고민해보겠습니다!

2024-09-20 07:46 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/DatePickerDialog.kt
> +    override fun onCreateView(
이전에 타프로젝트에서 언급주셨던 부분이라 기억하고 있습니다.
로직 변경을 하면서 고려해보겠습니다.

2024-09-20 07:48 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/DatePickerDialog.kt
> +            displayedValues=((minValue..maxValue).map{"$it 년"}.toTypedArray())
numberPicker의 출력 형태로 인하여 Array로 캐스팅을해야 2024년 과 같은 형태로 출력할 수 있습니다.

2024-09-20 07:49 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/DatePickerDialog.kt
> +            // 연도 선택에 따른 월의 최대값 동적 설정
현재를 기준 다음년도의 2월까지가 기준으로 2024년일 경우에는 2025년 3월부터의 데이터는 존재하지 않아 최대값 설정을 진행하였습니다.

2024-09-20 07:50 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/DatePickerDialog.kt
> +            )
Dialog 구현에 앞서 MVVM 형태의 로직을 고려를 제대로 못하고 익숙한 방식으로 진행한거 같습니다.
로직을 수정해보겠습니다.

2024-09-26 00:41 UTC, m6z1 reviewed
MVVM 로직 구조에 대해서 다시 답변드렸습니다! 
코멘트 확인 부탁드려용

2024-09-26 00:41 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/DatePickerDialog.kt
> +        val view = binding.root
뷰바인딩을 초기화하고 반환 이후에 binding 객체를 사용하는 게 더 안전해보입니다!

2024-09-26 00:41 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/DatePickerDialog.kt
> +
초기값을 설정하는 건 onCreateView에서의 역할이 아닌 것 같습니다! 뷰바인딩이 세팅이 끝난 후인 onViewCreated로 옮겨보시죵

2024-09-26 00:41 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/DatePickerDialog.kt
> +    private val listener: ScheduleClickListener
생성자로 연도, 월, 클릭리스너를 받아야 할까요?

2024-09-26 00:41 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/DatePickerDialog.kt
> +            dismiss()
지금 방법은 MVVM 패턴이 아닌 것 같습니다! view 변경 시 ViewModel 내 메서드 호출 > fragment 에서 viewModel의 파라미터 observing > 학사일정 변경
이 로직대로 가야 할 것 같아요! 지금 로직은 interface로 직접 값을 넘기는 것 같습니다.

2024-09-26 00:41 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/DatePickerDialog.kt
> +        return BottomSheetDialog(requireContext(), R.style.CustomBottomSheetDialogTheme)
이 친구는 onCreateView에서 작동을 안 하나요 ? 
onCreateView에 
``` kotlin
setStyle(STYLE_NORMAL, R.style.WebsosoDialogTheme)
```
요 코드 넣어보시면 될 거예요

2024-09-26 00:41 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/ScheduleClickListener.kt
> +}
인터페이스를 제거해보시죠!

2024-09-26 00:41 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/ScheduleFragment.kt
> +    }
이 인터페이스를 만들지 않고, 다이얼로그에서 버튼을 클릭했을 때 viewModel.setPickedDate 를 사용하면 될 것 같아요

2025-01-15 08:12 UTC, closed without merging